### ISSUE TITLE
Notification Alert

### ISSUE THREAD

**Issue by PhrozenByte** [muffinmad/pidgin-im-gnome-shell-extension#15]
First of all: Great extension, thank you!

I would like to use your extension together with [Notification Alert](https://extensions.gnome.org/extension/258/notifications-alert-on-user-menu/), a extension that lets the user menu blink, when unread notifications are present. Unfortunately it seems, that your extension doesn't mark chat notifications as unseen/unread, thus Notification Alert doesn't work.

I'm using GNOME 3.14.2 on Debian Jessie.

**Comment by muffinmad** [comment]
Just installed Notification Alert extension and it works fine for me. It blinks when tehre are conversation with unread messages (marked with overlay icon with number of messages)
![2015-01-13 10 48 30](https://cloud.githubusercontent.com/assets/2702727/5718038/d0afa1aa-9b11-11e4-8aef-103fc013339b.png)

**Comment by PhrozenByte** [comment]
Initially I even didn't got the number of messages, after a little more research, I found out, that this is caused by an incompatibility with the "Force showing details for all notifications" feature of [Panel OSD](https://extensions.gnome.org/extension/708/panel-osd/). Now everything works great. Thank you!
