### ISSUE TITLE
Custom icons are not used for buddy icons in notifications. 

### ISSUE THREAD

**Issue by chrissnyder2337** [muffinmad/pidgin-im-gnome-shell-extension#16]
When a custom icon is set for a buddy. It is not used in the notifications or the search.

![workspace 1_007](https://cloud.githubusercontent.com/assets/5921135/5920882/f343f5e8-a60d-11e4-8647-e9c31d56b5f7.png)

**Comment by muffinmad** [comment]
Fixed with this commit: https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/fb9dbfdf02b66256f2fbfe2e842fc7c751118666
