### ISSUE TITLE
System Tray buddy icon dissappears after closing pidgin chat window

### ISSUE THREAD

**Issue by cyberalex4life** [muffinmad/pidgin-im-gnome-shell-extension#17]
I know this is not a bug, it is more like a pull request (I can't seem to make a pull request anymore). If I use this extension I would not to to mess too much with pidgin windows. So there 2 things I ask from you:
1. closing pidgin buddy conversation window doesn't close the buddy conversion icon in the tray.
2. opening buddy conversation window will automatically create tray conversation icon and 1 aplies

**Comment by muffinmad** [comment]
Tray icon removed as soon as conversation (not window) closed. There are "Close IMs immediately when the tab is closed" option in Pidgin preferences under "Conversations" tab. Try to uncheck it.

**Comment by cyberalex4life** [comment]
ok, I think this would solve part 1, But part 2?

**Comment by muffinmad** [comment]
Same thing. Tray icon is linked to conversation, not conversation window. So it will be created when you send/recieve first message.

**Comment by cyberalex4life** [comment]
I kind of noticed a few minutes ago, but somebody started talking to me and didn't have time to reply. Sorry for troubling you, Nice job you did with with this project

**Comment by muffinmad** [comment]
No problem. Thanks!
