### ISSUE TITLE
Less notifications when using IRC

### ISSUE THREAD

**Issue by ollb** [muffinmad/pidgin-im-gnome-shell-extension#18]
It seems there are too much notifications when using IRC. 
It seems a notification is raised each time someone sends a message.
It should be enough to raise a notification when someone writes to me or highlights me in a channel.

**Comment by muffinmad** [comment]
It's strange.
It was fixed by this commit: https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/b799611538551235c1a089b528d995c237565f34
Same issue: https://github.com/muffinmad/pidgin-im-gnome-shell-extension/issues/4

**Comment by ollb** [comment]
Indeed, thanks to b799611 only messages sent to me (or with highlight) create a "full notification". 

However, all messages (even those not sent to me) are inserted in the notification bar (channel by channel). After a while, the notification bar is full of conversations I don't want to be notified of.

**Comment by muffinmad** [comment]
Please, view this commit: https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/704599fd50b8dce90ad501ce1bcbe96bebac4bc7
I'm propose this behaviour: if option "Track only highlighted messages for chats" is enabled, chat source will be created only on highlighted message, than all messages will be added to chat source in message tray until you close it.

**Comment by ollb** [comment]
Great ! Exactly what I wanted. Thanks.
