### ISSUE TITLE
Does not support Gnome Shell 3.16

### ISSUE THREAD

**Issue by alexozer** [muffinmad/pidgin-im-gnome-shell-extension#19]
Maybe in the future?

**Comment by muffinmad** [comment]
It must already.
With this commit: https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/7650321d41f678c3f3c9f0f942b3c0fd65194f12
Also version 21 of extension already aproved on extensions.gnome.org
What version of extension do you use?

**Comment by alexozer** [comment]
Okay, maybe I'm doing something wrong. Will try installing from extensions.gnome.org
