### ISSUE TITLE
UTF-8 or what problem

### ISSUE THREAD

**Issue by 0liUms** [muffinmad/pidgin-im-gnome-shell-extension#20]
Hi,
I've seen than if I let a notification without touch it, sometimes it print in first « d'ac » and 1 or 2 minutes later it's transformed in « d&apos;ac ».
( edit : I mean, from « d'ac » to « d & apos ; ac » without spaces )

Strange !
liUms

**Comment by muffinmad** [comment]
Can you record video with this, please?

**Comment by 0liUms** [comment]
Yes I do it asap

**Comment by 0liUms** [comment]
Oh yes I didn't see than github interpret & apos ; ^^
here is the video ! http://jirafeau.net/f.php?h=3A_nHRfY&p=1
I'm running gnome shell on archlinux, my conf files are probably messy but I don't think this bug come from my side …?

**Comment by muffinmad** [comment]
Yes, it's not on your side. It's gnome-shell and the extension markup behaviour. AUR and EGO updated with fixed version, but EGO is waiting for review.

**Comment by 0liUms** [comment]
yes thank you ! :)
