### ISSUE TITLE
notification bar : too many clicks needed to switch discussion

### ISSUE THREAD

**Issue by ollb** [muffinmad/pidgin-im-gnome-shell-extension#21]
Inside notification bar, when clicking on an discussion icon and then another one, the new discussion doesn't appear. Two other clicks are needed the switch discussion : the second one makes old discussion disapear, and the last one finaly shows the wanted discussion.

**Comment by muffinmad** [comment]
I think it's related to https://github.com/muffinmad/pidgin-im-gnome-shell-extension/issues/22
Pidgin open conversation but not make it focused

**Comment by ollb** [comment]
My explanation is missleading see attached video.

![issue-21](https://cloud.githubusercontent.com/assets/5952064/7769384/662c7f10-0083-11e5-97b5-223fb346746b.gif)

**Comment by muffinmad** [comment]
I see now, thanks. It's gnome-shell behavior. I suspect empathy notifications works the same way.
Notification area is moved to top on GS 3.16, I don't think it's will be fixed or improved.
