### ISSUE TITLE
Cannot respond to message after banner disappears on gs 3.16

### ISSUE THREAD

**Issue by dramforever** [muffinmad/pidgin-im-gnome-shell-extension#25]
After the notification goes into the notification menu, I can no longer type in messages.

However, I don't know if it's fixable. I think you can try to integrate the extension into the bottom tray just like pidgin itself.

**Comment by muffinmad** [comment]
Empathy notifications works the same way. It's GNOME Shell behaviour.

**Comment by aurabindo** [comment]
I too miss this feature. This is was one feature which made me tell that gnome shell stays out of the way. While I am doing something, if someone texts me, I can send a quick reply without having to worry about switching to the virtual desktop where pidgin chat window is.

Is there no way to fix it ?

**Comment by muffinmad** [comment]
I think there are at least two ways:
1. Feature request to gnome-shell
2. Implement own conversation window instead of pidgin one

**Comment by greatquux** [comment]
I'm flabbergasted that this feature was removed in gnome-shell 3.16.  This was probably the only reason I even used gnome shell, I am IM'ing people a lot, and this was an incredible useful feature to go down to the message tray window and just type without having to switch to my pidgin or empathy window. Obviously not your problem, you are just inheriting what they have, I just can't believe it.

**Comment by aurabindo** [comment]
I just made a feature request with gnome 
https://bugzilla.gnome.org/show_bug.cgi?id=757588

**Comment by muffinmad** [comment]
@aurabindo Thanks!

**Comment by dramforever** [comment]
@aurabindo Thanks a lot for taking care of this!

**Comment by cyberalex4life** [comment]
This is what I changed for reopening notification:
```
open: function(notification) {
		if (ExtensionUtils.versionCheck(['3.16', '3.18'], Config.PACKAGE_VERSION)) {
			Main.overview.hide();
			Main.panel.closeCalendar();
		}
		//this._client.proxy.PurpleConversationPresentRemote(this._conversation);
		
		Mainloop.timeout_add(300, Lang.bind(this, this.notify));
		this._pendingMessages.push(message);
		this.countUpdated();
				
			
	}, 
```
aproximateley from line 287 in
```
function Source(client, account, author, conversation) {
	this._init(client, account, author, conversation);
}
Source.prototype = {
	__proto__: MessageTray.Source.prototype,
.............................
};
```

**Comment by cyberalex4life** [comment]
An I would make some suggestions (or requests):
1. if possible, the solution I presented be completed by adding a submenu to the notification with 2 options: first - to present pidgin conversation window, second: to show window list.
2. again, if possible, and once 1 is implemented, to change the behaviour of buddy on click from opening a new convesation window to presenting a notification like the above mentioned. 
These could work OK with with 'Hide new IM convesation' set to 'Always'.

**Comment by muffinmad** [comment]
Reopen notification instead of presenting pidgin conversation window can be configurable option.

**Comment by cyberalex4life** [comment]
I agree...
So the other one

**Comment by muffinmad** [comment]
There are option "Reopen banner..." in version 26
Added with this commit https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/a2f080f89ed750a3014e9316f737f9281d473ea2

**Comment by greatquux** [comment]
Awesome!! I guess this takes a little time to come through the official channels?

**Comment by muffinmad** [comment]
@greatquux Archlinux AUR package is updated already. Version 26 is currently "Unreviewed" on extensions.gnome.org.

**Comment by muffinmad** [comment]
@greatquux Version 26 on EGO now

**Comment by greatquux** [comment]
This is so great!! I hope it continues working in the newest versions of GNOME and they don't break it again! But for now at least I'm very happy. :)

**Comment by greatquux** [comment]
looks like this can be resolved

**Comment by muffinmad** [comment]
@cyberalex4life Can you please arrange your requests as separate issues so i can close this one?

**Comment by cyberalex4life** [comment]
in about 12-24 hours @muffinmad , I have to sleep now :)

**Comment by cyberalex4life** [comment]
You can close this issue. The other 2 issues are:
#33  
#34 
Thank you for your work @muffinmad
