### ISSUE TITLE
Package is not marked as recommendation when you have both Shell and Pidgin

### ISSUE THREAD

**Issue by pvsomebody** [muffinmad/pidgin-im-gnome-shell-extension#26]
As it says in the header. Not being a recommended package leads to people who have Pidgin and Gnome Shell and could potentially benefit from this extension, but not aware of its existence to skip it. Is there anything you could do about it?

Here is the view of the issue by Red Hat people: https://bugzilla.redhat.com/show_bug.cgi?id=1242620

**Comment by muffinmad** [comment]
I'm surprised that there are RPM package for this extension.

Only package maintainer can mark other package as recomendation, so i can't do that.

**Comment by pvsomebody** [comment]
All right, sorry to bother you.

**Comment by muffinmad** [comment]
No problem
