### ISSUE TITLE
Integrating the system status

### ISSUE THREAD

**Issue by 2i** [muffinmad/pidgin-im-gnome-shell-extension#27]
Gnome provides an API for setting an user wide availability status (available, busy, offline) for providing an central way of controlling the user status in all connected applications. This is used by some other extensions. This extension could integrate this status into Pidgin.

Some information about the API:
- https://people.gnome.org/~mccann/gnome-session/docs/gnome-session.html#org.gnome.SessionManager.Presence
- https://github.com/MrTheodor/gnome-shell-ext-SkypeNotification/blob/master/SkypeNotification%40krajniak.info/extension.js

**Comment by muffinmad** [comment]
How to change the status in gnome 3.16?

**Comment by 2i** [comment]
I did not test/verify it, but that’s what I found:
```
presence = new imports.misc.gnomeSession.Presence();
presence.SetStatusSync(imports.misc.gnomeSession.BUSY);
presence.SetStatusRemote(imports.misc.gnomeSession.BUSY);
```
I do not know the difference between these methods, they are documented nowhere.
I used the looking glass to examine the gnome shell objects.

**Comment by muffinmad** [comment]
I don't see any user-wide status in recent gnome-shell versions
