### ISSUE TITLE
[GNOME-Shell 3.16] Blinking icon when replied from notification bar

### ISSUE THREAD

**Issue by phatina** [muffinmad/pidgin-im-gnome-shell-extension#28]
When I reply to a new message right in the notification area, I can still see a blinking icon in the (legacy) tray. I expect the tray icon stop blinking and pidgin behave as if I replied in the conversation window.

**Comment by muffinmad** [comment]
This issue is mentioned in README:
> Messages appear unseen in Pidgin after expanding notification in message tray. Don't know how to set unseen state in Pidgin

**Comment by phatina** [comment]
OK, thanks. :)
