### ISSUE TITLE
Tag current version?

### ISSUE THREAD

**Issue by DamienCassou** [muffinmad/pidgin-im-gnome-shell-extension#30]
Hi,

to facilitate packaging for distributions, could you please tag the current commit with git? Something like `v0.1.0` if you want.

Thanks

**Comment by muffinmad** [comment]
Yes, sure. https://github.com/muffinmad/pidgin-im-gnome-shell-extension/releases/tag/v1.0

**Comment by DamienCassou** [comment]
Thanks, this helps.
