### ISSUE TITLE
"Notify buddies that you are typing to them" setting not respected

### ISSUE THREAD

**Issue by nunocastromartins** [muffinmad/pidgin-im-gnome-shell-extension#35]
There is a Pidgin setting to `Notify buddies that you are typing to them`.
I tested with a friend and, when typing from this extension's chat box, he could always tell that I was typing, even though I have that setting unticked.

Would it be possible for this extension to access the value of that setting and respect it?
Thank you for the excellent work so far!

**Comment by muffinmad** [comment]
@nunocastromartins Thanks for participation!
Check out [v1.0.1](https://github.com/muffinmad/pidgin-im-gnome-shell-extension/tree/v1.0.1).
Updates to EGO and AUR will be ready soon.
