### ISSUE TITLE
Cannot write special characters / _fixText does not work?

### ISSUE THREAD

**Issue by null-von-sushi** [muffinmad/pidgin-im-gnome-shell-extension#40]
If I write "  don't  " into the notification, it changes it to " don&apos;t  ".
I have no idea what this is causing. I looked at the extension (not that I understand any of it), but afaik "_fixText()" in extension.js should prevent this, no?

System:
Antergos with kernel 4.7.4-1
Pidgin 2.11.0 (libpurple 2.11.0)
Using Telegram Account thanks to telegram-purple 1.3.0-1

If any other information is needed I will be happy to provide that.

**Comment by muffinmad** [comment]
I can't see how " don't " differs from " don't ".
Can you take screenshot, please?
Outgoing text is passed to GLib.markup_escape_text.

**Comment by Null-Senpai** [comment]
Err, sorry about that. It seems Github changed the second "don't" (I wrote d-o-n-&-a-p-o-s-;-t, but as soon as I click 'update comment' github transforms the text into the normal, readable word "don't".
![screenshot from 2016-10-06 19-52-36](https://cloud.githubusercontent.com/assets/13616397/19166290/dbeb9e4a-8bfe-11e6-8ff0-bb7cdc1b2322.png)

**Comment by muffinmad** [comment]
I think is relative to telegram-purple. Can you please check it with other protocols?

**Comment by darthoctopus** [comment]
I can confirm that this is an issue with the GNOME shell extension, rather than telegram-libpurple. I can send apostrophes with Pidgin just fine; only messages sent through the gnome shell extension get HTML entities inserted.

**Comment by muffinmad** [comment]
@darthoctopus Looks like pidgin has special behavior about `&apos;`: https://bitbucket.org/pidgin/main/commits/1929fae118e5fbf1a71836531caddd63ed385fab

I think avoiding escaping `'` on replying via extension may help.
