### ISSUE TITLE
search provider is not providing all matches

### ISSUE THREAD

**Issue by brianjmurrell** [muffinmad/pidgin-im-gnome-shell-extension#43]
When I click on Activities and then start searching for a name of a buddy in pidgin, it is not showing all matches.  It in fact shows pretty bad matches.  Perhaps matching buddies based on them being a buddy of an account of mine, when I search for my own name, which happens to be the name of my son who is also a buddy.

So to be clear, searching for mine and my son's name (which are the same) brings up all kinds of buddies that don't match that name (but of course are buddys of that name) but doesn't bring up my son's name.

**Comment by muffinmad** [comment]
There was https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/a0291ae032130630645fb6ddc696f3a0e99852c2 and https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/0eeadd2859cc40448f57b20e538c3cf4bad92c5d.
As for now search terms is applied to buddy's alias, handle and account name, so one can't easilly search "John" with handle "john@domain.com" on account "john@mydomain.com".
I think prefixed search terms may solve the problem. For example, search term without prefix will search aliases, term prefixed with "@" will search handles and term prefixed with "#" will search accounts.

**Comment by brianjmurrell** [comment]
> There was a0291ae and 0eeadd2.

I don't think either of these are relevant.

The problem is quite simple.  If I search (in the gnome activities screen, to be clear) for a buddy, by name, say "brian", because even though my name is brian, i do have buddys with that name.  So I search for "brian" and I get a number of hits, none of which have "brian" anywhere in their buddy name, be it their real name, their handle, etc.  But those buddies of course are attached to an account (of mine) with the name brian in it.  So I will get a search result of "Fred Flintstone via brian...".  I'm only getting that search result, presumably because _Fred Flintsone_ is a buddy of my own accounts which has "brian" in the account name.

If I search for a name other than "brian", I get some pretty valid looking results for people with the name that I searched for.

So the problem seems to be searching for buddies who's name might be the same as your own.  The results need to have matches by one's own account name filtered out.

**Comment by muffinmad** [comment]
> But those buddies of course are attached to an account (of mine) with the name brian in it.

Exactly this behaviour was added by the commit https://github.com/muffinmad/pidgin-im-gnome-shell-extension/commit/0eeadd2859cc40448f57b20e538c3cf4bad92c5d

**Comment by brianjmurrell** [comment]
> Exactly this behaviour was added by the commit 0eeadd2

No.  You still don't seem to be understanding the problem.  The problem is that my IM account has my name ("brian") in it.  It could be for example a jabber account of "brian@example.com".  When I search for buddies with the name "brian" I get all kinds of hits that don't have "brian" in *their* name.  The reason they are being matched is because they are a jabber buddy in my "brian@example.com" account.

So furthering the example, using my "brian@example.com" jabber account, I connect to a buddy named "fred@bar.com".  When I search for buddies using "brian" as the search term, the "fred@bar.com" account comes up as a hit, not because the buddy's name is brian, or has brian anywhere in it but simply because "fred@bar.com" is a buddy of the "brian@example.com" account.

**Comment by brianjmurrell** [comment]
Oh wait.  Maybe I am misunderstanding you...

> Exactly this behaviour was added by the commit 0eeadd2

You are saying that that commit added the code to make matches based on the name in my account?

Perhaps some kind of search notation is needed to signify which account attribute a search term is to apply to?  Like maybe _@term_ means _term_ is searched for items that 0eeadd2 is matching.

**Comment by muffinmad** [comment]
Yes, prefixed search terms is what I'm talked about in my first comment.

**Comment by brianjmurrell** [comment]
Indeed.  Apologies for not understanding that the first time around.

**Comment by muffinmad** [comment]
Released in the version 31.
https://github.com/muffinmad/pidgin-im-gnome-shell-extension/releases/tag/v1.0.3

**Comment by brianjmurrell** [comment]
Yes, this seems much better.  Cheers!
