### ISSUE TITLE
broken in gnome 3.26?

### ISSUE THREAD

**Issue by WhatsThePlan** [muffinmad/pidgin-im-gnome-shell-extension#45]
is it possible it is broken in 3.26? extension still loads and search still works but i get no notifications any more from pidgin?

**Comment by muffinmad** [comment]
Probably yes.

There are errors in journal like this
```
JS ERROR: Exception in callback for signal: DisplayedImMsg: TypeError: Tp is null
```
everytime trying to display notification banner

**Comment by greatquux** [comment]
i'm glad someone else found this before i did, i was planning to upgrade tonight and i love this extension far too much :)

**Comment by muffinmad** [comment]
Sorry, I misled you.
It was my setup issue - telepathy-logger was not installed.
With telephaty-logger installed everything works fine.

**Comment by WhatsThePlan** [comment]
that was indeed problem, thanks!
