### ISSUE TITLE
Not working on gnome 3.32

### ISSUE THREAD

**Issue by greatquux** [muffinmad/pidgin-im-gnome-shell-extension#50]
Upgraded to Ubuntu 19.04 last night with GNOME 3.32.  The extension loads but no longer puts any notifications in the system tray.  Logs are getting these messages:
```

Apr 22 09:26:55 ossy gnome-shell[32527]: JS WARNING: [/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js 146]: reference to undefined property "_init"
Apr 22 09:26:55 ossy gnome-shell[32527]: JS ERROR: Exception in callback for signal: DisplayedImMsg: TypeError: MessageTray.Source.prototype._init is undefined
                                         _init@/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:146:3
                                         _init@/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:364:3
                                         ImSource@/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:336:2
                                         _handleMessage@/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:926:14
                                         _messageDisplayed@/home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:951:3
                                         bind/<@resource:///org/gnome/gjs/modules/lang.js:97:16
                                         _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                         _convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:117:5

```
They didn't get rid of this, did they?

**Comment by muffinmad** [comment]
Well...

> ES6 finally adds standard class syntax to the language, so we can
replace our custom Lang.Class framework with the new syntax.

[This commit](https://gitlab.gnome.org/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca#a8805c753d4397f7f48968ce9fb35a0633322d5a).

*Sigh*

**Comment by greatquux** [comment]
mmmm syntactic sugar ;)

**Comment by muffinmad** [comment]
Try `extension.js` and `dbus.js` from [this WIP branch](https://github.com/muffinmad/pidgin-im-gnome-shell-extension/tree/gs332).

Proper version will be ready after i completely get rid of `imports.lang`

**Comment by greatquux** [comment]
Works perfectly!! Thanks so much for fixing this so quickly. I know you cleaned up some other things but didn't think you would have to make so many changes just to switch to actual constructors/destructors. It's really a very useful extension for me!

**Comment by muffinmad** [comment]
I deleted the code that supported the older version of GS. Version [32](https://github.com/muffinmad/pidgin-im-gnome-shell-extension/releases/tag/v32) now supports only GS 3.32.

New version is uploaded for review to EGO.

Closing this issue.

Thanks for report!
