### ISSUE TITLE
Compatibility with gnome-shell 3.36 ?

### ISSUE THREAD

**Issue by teymour** [muffinmad/pidgin-im-gnome-shell-extension#51]
The plugin seems to fail to relay the notifications of pidgin with gnome-shell in version 3.36. Some interactions provoke a notification "Pidgin ready" but the usual notification box allowing the chat has disappear :(

To solve my problem i've downgraded gnome-shell to the version 3.30 (from the Debian testing package to the stable one).

**Comment by muffinmad** [comment]
Can confirm.

I see errors in `journalctl /usr/bin/gnome-shell -f` like `Exception in callback for signal: DisplayedImMsg: Error: Tried to construct an object without a GType`.

**Comment by muffinmad** [comment]
Please try recent version https://github.com/muffinmad/pidgin-im-gnome-shell-extension/releases/tag/v34

**Comment by teymour** [comment]
It works for query messages, but when the notification comes from a chan, an error is trigered : 

     JS ERROR: Exception in callback for signal: DisplayedChatMsg: TypeError: this._cbNames is undefined
