### ISSUE TITLE
Question - support for gnome 3.36.1 ?

### ISSUE THREAD

**Issue by yuriw** [muffinmad/pidgin-im-gnome-shell-extension#54]
Installed it on ubuntu 20.04 gnome 3.36.1 and see nothing at all, no icon in the bar no notifications.
Is it supported yet?

**Comment by greatquux** [comment]
That's strange because it is working for me. muffinmad did have to issue a new version, but I think the version on extensions.gnome.org is current.  I think you do need to completely log off and back in though.

**Comment by yuriw** [comment]
I restarted pidgin and so still no love, will try to reboot later

**Comment by yuriw** [comment]
After reboot still no go

?!

**Comment by yuriw** [comment]
@greatquux what am I to see?  can you paste and screenshot of an icon on the bar ?

**Comment by muffinmad** [comment]
There are not icon on the bar. Extension provide only notifications and search provider (search your buddies in Activities).

Version 36 which was adopted to run in GS 3.36 (#51 #52) is active on [EGO](https://extensions.gnome.org/extension/782/pidgin-im-integration/).

Some time ago were reports that you need to install `gir1.2-telepathyglib-0.12` and `gir1.2-telepathylogger-0.2` on Ubuntu 17.10.

Also do you see any error messages in `journalctl $(which gnome-shell) -f` related to the extension?

**Comment by yuriw** [comment]
@muffinmad I see errors:

`May 05 13:45:55 yuriw-RH2 gnome-shell[1852]: Error connecting to Nautilus
May 05 13:45:56 yuriw-RH2 gnome-shell[1852]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 05 13:45:56 yuriw-RH2 gnome-shell[1852]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 05 13:46:00 yuriw-RH2 gnome-shell[1852]: Power state changed: fully charged
May 05 13:46:00 yuriw-RH2 gnome-shell[1852]: Could not create transient scope for PID 8043: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8043 does not exist.
May 05 13:46:00 yuriw-RH2 gnome-shell[1852]: Could not create transient scope for PID 8046: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8046 does not exist.
May 05 13:46:00 yuriw-RH2 gnome-shell[1852]: Could not create transient scope for PID 8049: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 8049 does not exist.
May 05 13:46:00 yuriw-RH2 gnome-shell[1852]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
May 05 13:46:03 yuriw-RH2 gnome-shell[1852]: pidgin-im-gs: TypeError: TelepathyClient.ChatNotification is not a constructor
`

**Comment by muffinmad** [comment]
Do you have `telepathy-glib` and `telepathy-logger` installed?

**Comment by yuriw** [comment]
Looks like I yes for `telepathy-glib` and no to `telepathy-logger`:

dpkg -l | grep telepathy-glib
ii  libtelepathy-glib0:amd64                                    0.24.1-2ubuntu1

dpkg -l | grep telepathy-logger

**Comment by muffinmad** [comment]
[Looks like](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/components/telepathyClient.js#L9) both of them are needed. Chances in full log (without `-f`) you will see "Telepathy is not available, chat integration will be disabled" message.

**Comment by yuriw** [comment]
Installed and reinstalled the plugin restarted pigin and still no love


May 05 14:04:18 yuriw-RH2 gnome-shell[1852]: JS WARNING: [resource:///org/gnome/shell/misc/extensionUtils.js 217]: reference to undefined property "metadata"
May 05 14:04:23 yuriw-RH2 gnome-shell[1852]: pidgin-im-gs: TypeError: TelepathyClient.ChatNotification is not a constructor

**Comment by muffinmad** [comment]
How do you install the plugin?

**Comment by yuriw** [comment]
Via https://extensions.gnome.org/

**Comment by muffinmad** [comment]
Can you please show extension metadata to verify extension version? E.g. `cat ~/.local/share/gnome-shell/extensions/pidgin@muffinmad/metadata.json`

**Comment by yuriw** [comment]
└──╼  $ cat ~/.local/share/gnome-shell/extensions/pidgin@muffinmad/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Integrate Pidgin IMs in the Gnome Shell message tray",
  "gettext-domain": "gnome-shell-extension-pidgin",
  "name": "Pidgin IM integration",
  "settings-schema": "org.gnome.shell.extensions.pidgin",
  "shell-version": [
    "3.36"
  ],
  "url": "https://github.com/muffinmad/pidgin-im-gnome-shell-extension",
  "uuid": "pidgin@muffinmad",
  "version": 36
}┌

**Comment by muffinmad** [comment]
Now I'm out of ideas :(

**Comment by yuriw** [comment]
:(

**Comment by muffinmad** [comment]
Manage to make it work on Ubuntu 20.04 after installing `gir1.2-telepathyglib-0.12` and `gir1.2-telepathylogger-0.2`.

To check if they are installed correctly, from terminal:
```
$ gjs
gjs> const tp = imports.gi.TelepathyGLib;
gjs> const tpl = imports.gi.TelepathyLogger;
```

There are must be no errors importing `TelepathyGLib` and `TelepathyLogger`

**Comment by yuriw** [comment]
Reinstalled `gir1.2-telepathylogger-0.2` see no errors, but no icon extension either

**Comment by muffinmad** [comment]
Extension provide only notifications and search provider (search your buddies in Activities). There are no icons provided by this extension.

**Comment by yuriw** [comment]
@muffinmad ok let me use pidgin for awhile ans see
Thank for you help !

**Comment by muffinmad** [comment]
Like this:

![screenshot](https://raw.githubusercontent.com/muffinmad/pidgin-im-gnome-shell-extension/master/pidgin-im-gs.png)

**Comment by yuriw** [comment]
so far seen none

**Comment by yuriw** [comment]
@muffinmad I don't see anything.
Any way to tail what's going on and test it ?

**Comment by muffinmad** [comment]
Just in case: did you restart gnome-shell after installing `gir1.2-telepathyglib-0.12` and `gir1.2-telepathylogger-0.2`?

**Comment by yuriw** [comment]
finally after reboot it works !
:)
