### ISSUE TITLE
Gnome 41 Support

### ISSUE THREAD

**Issue by JKomoroski** [muffinmad/pidgin-im-gnome-shell-extension#57]
Will we see a formal bump to your package to gnome 41? 
It shows as Gnome 40 on extension.gnome.org.

**Comment by muffinmad** [comment]
Does it work on Gnome 41?

**Comment by JKomoroski** [comment]
> Does it work on Gnome 41?

I got caught up at work. I will verify and get back to you.

**Comment by JKomoroski** [comment]
I was able to manually install, update the `metadata.json` to tell it that gnome-shell 41 was supported. Restarted the shell, and enabled the extension without issue. The extension appears to work but I don't know all the features.
