### ISSUE TITLE
GNOME 45 Support

### ISSUE THREAD

**Issue by greatquux** [muffinmad/pidgin-im-gnome-shell-extension#62]
It looks like GNOME 45 is going to require a fair amount of extra work to port extensions to. I'm not sure how this will affect this beloved extension, but I wanted to create an issue to bring it up.  I would totally kick in some dough (I mean, up to a point!) to make it worth your time.  Hopefully it won't be too bad for a relatively smallish extension like this (dash-to-dock has got a lot of work to do!) 
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by greatquux** [comment]
well, i have attempted to port this to GNOME 45 at my fork here 
https://github.com/greatquux/pidgin-im-gnome-shell-extension
BUT it doesn't work.   When the extension loads up, I get

Nov 03 15:04:43 mike-pc-i440fx-8-1 gnome-shell[85221]: pidgin-im-gs: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name im.pidgin.purple.PurpleService was not provided by any .service files

and it doesn't display any notifications when a chat pops up in pidgin. 

Later on, if the desktop goes idle and i have to unlock it, i get
Nov 03 15:15:49 mike-pc-i440fx-8-1 gnome-shell[85704]: pidgin-im-gs: TypeError: TelepathyClient.ChatNotification is not a constructor

Now, I'm pretty much using "cargo cult" techniques to try to port this, so in some sense it is not a surprise it doesn't work, but I do hope someone can come along and help me figure it out! :)

**Comment by muffinmad** [comment]
Hi @greatquux 

I've started working on GS 45 support in #63

The preferences dialog is already working! :)

I see the `TelepathyClient.ChatNotification is not a constructor` also. This is because the `TelepathyClient` is not exporting `ChatNotification` and I need to implement own chat notification. It will take a little more time.

**Comment by greatquux** [comment]
Wow, that's great news! Even better news to hear from you, I am happy you're safe.  Reminds me to donate some money to the army. :) If you happen to have a KoFi link to I'd definitely throw you a nice tip, this is a great extension.  I expect eventually they'll deprecate Telepathy altogether which would suck because being able to reply to IMs with this extension is so useful.  Maybe by then there'll be some other solution.  
It would be interesting to compare your code to mine because as I said I was basically manipulating symbols without fully understanding everything.. it is one way of learning I guess! Hope they fix this bug too:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/2040453
since it made it hard to debug extensions if you can't really restart GS without having to close everything anyway.

**Comment by muffinmad** [comment]
I've merged #63. I believe it should work with GS 45 now. I've also uploaded the new version to extensions.gnome.org, so it should be available once it will be reviewed.

> If you happen to have a KoFi link to I'd definitely throw you a nice tip

No, I do not have one. But thank you :)

> I expect eventually they'll deprecate Telepathy

It's not a problem now. Pidgin integration does not depends on Telephaty components anymore.

> It would be interesting to compare your code to mine

Sure, fill free to create PR :)

Thanks for your participation!

**Comment by greatquux** [comment]
Oh I'll be rescinding that pull request, it was obvious waaaayyyy more work had to be done to convert to GS45 that I ancitipated. I thought it might just be some syntactic sugar but it seems like a lot of extensions require a whole re-architecture to work, basically because of the required enable() method and having to sub-class an existing class (past a certain level of abstraction I'm not too comfortable lol).  I was having enough trouble trying to pass around an extension object to look up the local directory, I hard-coded the path to dbus.xml while I see you just pasted in the text!  And having to replace Telepathy... yeah.  Thank you again for this and I'll test this out on my VM soon.
